### ISSUE TITLE
Simply loading a sytem with lively.modules should not warn about "possible EventEmitter memory leak"

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.notifications#1]
That happens when running in nodejs.

https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n

(if warning appears then it should only be when there is a real possible leak)

**Comment by levjj** [comment]
I agree that NodeJS should not warn when there are simply 10 event listeners (this limits seems ridiculously low). However, where would be the right place to fix it and should the limit be higher or should there be no warning at all?

I submitted a [one-line fix for lively.lang](https://github.com/LivelyKernel/lively.lang/pull/1) that sets this limit to 10000. Independent of the exact limit, there could always be memory leaks that we miss. I'm still hoping that there will be weak references at some point.

**Comment by rksm** [comment]
Thanks!
